name: e2e-tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install

      - name: Run local project in dev and execute e2e tests
        run: yarn run e2e:ci

      - name: Create Directory for Combined E2E test report
        if: always()
        run: mkdir combined
        working-directory: cypress/TestReport

      - name: Merge Cypress Reports
        if: always()
        run: yarn run merge:reports

      - name: Generate HTML report
        if: always()
        run: yarn run create:html:report

      - name: Save test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reporter
          path: cypress/TestReport
